name: ci

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v6
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: ğŸ˜‰ Format
        run: deno task test:fmt
      - name: ğŸ˜‹ Lint
        run: deno task test:lint
  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v6
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: ğŸ§ Type Check
        run: deno task check
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v6
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: ğŸ˜ Test
        run: deno task test:coverage
